name: Next Deployment

on:
  push:
    branches: [production]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ubuntu
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          cd /home/ubuntu/services/blog-starter
          git fetch origin
          git checkout production
          git pull
          sudo docker build -t blog-starter:latest .
          sudo docker stop blog-starter-container || true
          sudo docker rm blog-starter-container || true
          sudo docker run -d --name blog-starter-container -p 4000:3000 blog-starter
          