name: Next Deployment

on:
  push:
    branches: [production]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        port: 22
        script: |
          cd /services/blog-starter
          git fetch origin
          git checkout production
          git pull
          docker build -t blog-starter:latest .
          docker stop blog-starter-container || true
          docker rm blog-starter-container || true
          docker run -d --name blog-starter-container -p 4000:3000 blog-starter
          